### ISSUE TITLE
[Bug] function attribute not working correctly get_game_metadata_by_game_id(game_id).game_key

### ISSUE THREAD

**Issue by hkingsley** [uberfastman/yfpy#50] opened 2023-12-07 15:38 UTC
## Description of Issue
function attribute not working correctly get_game_metadata_by_game_id(game_id).game_key

so unable to use query.get_league_info()

#### Yahoo Fantasy Sports League ID
122731

#### Yahoo Fantasy Sports League Privacy
Public

#### Operating System/Environment
Ubuntu

#### Other
Any other setup/environment/configuration information you might deem potentially relevant.
![Screenshot 2023-12-07 153357](https://github.com/uberfastman/yfpy/assets/13963761/fbf00db9-c2f2-407f-8785-d32cd52469f6)

**Comment by hkingsley** [comment] 2023-12-07 15:43
looks like its affecting more than just query.get_league_info() also query.get_league_standings()
![Screenshot 2023-12-07 154212](https://github.com/uberfastman/yfpy/assets/13963761/795beb74-210a-4c95-984e-fb7a0c75006d)

**Comment by uberfastman** [comment] 2023-12-08 21:58
Hi @hkingsley, thanks for the bug report. With the latest major version release of YFPY, I made a change in how you set up the `YahooFantasySportsQuery` object such that it now _requires_ you to provide the `game_code` as part of instantiation. You can use `nfs`, `mlb`, `nhl`, or `nba` for the respective sports. What I'm guessing is happening though is if you didn't provide that positional argument but then had subsequent arguments, then the new class signature was picking up a value set for `all_output_as_json_str`, which would trigger it to be `True`, and thus all of our output would be converted to JSON strings instead of YFPY objects. 

If you can show me how you were instantiating your `YahooFantasySportsQuery` object I can confirm if my suspicions are correct. I tried running all of the above methods with your league and had no issues retrieving the info as expected, so I think it might just be an issue with the setup due to that change I made in this last major version release.

**Comment by hkingsley** [comment] 2023-12-09 14:28
@uberfastman Thank you for getting back to me! This is how i've instantiated `YahooFantasySportsQuery`
![image](https://github.com/uberfastman/yfpy/assets/13963761/3b4769f3-d540-4cbc-a828-e6382567d06f)

**Comment by uberfastman** [comment] 2023-12-09 15:57
Ah phew, I was worried for a moment that something was broken. You need to just set `all_output_as_json_str=False` (or just exclude it as it defaults to False) and you should be all set.

I'm closing this but if anything persists just reopen it and add a comment!

**Closed** 2023-12-09 15:57 UTC
Labels: bug

**Comment by hkingsley** [comment] 2023-12-09 18:54
@uberfastman Thank you all sorted

**Comment by uberfastman** [comment] 2023-12-09 19:12
Great, glad it's sorted! Thanks for using YFPY!
